apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Netology Kubernetes</title>
    </head>
    <body>
      <h1>ConfigMap работает</h1>
      <p>Страница подключена через ConfigMap</p>
    </body>
    </html>