graph TD
    A("Интернет")

    subgraph cl[Yandex Cloud]
        direction TB

        B1("Network Load Balancer")
        B2("Application Load Balancer")

        %% Точки распределения - маленькие кружки
        D1(( )):::junction
        D2(( )):::junction

        subgraph gr[Instance Group]
            direction LR
            E1[VM1]
            E2[VM2]
            E3[VM3]
        end
    end
        A --> B1
        A --> B2
        B1 --> D1
        B2 --> D2
        D1 --> E1
        D1 --> E2
        D1 --> E3
        D2 --> E1
        D2 --> E2
        D2 --> E3

        classDef junction fill:#333333,stroke:#333333,color:#333333
        class D1,D2 junction

        classDef purpleStyle color:#FFFFFF, fill:#AA00FF, stroke:#AA00FF
        class E1,E2,E3 purpleStyle
        style cl color:#FFFFFF, fill:#FFAE42, stroke:#F9F8BB
        style gr color:#000000, fill:#EDFF21, stroke:#AA00FF

