graph TD
    YC[h-devops]

    subgraph Yandex Cloud
        OS[Object Storage]
        CC[Compute Cloud]

        IMG[image.jpg]
        IG[Instance Group<br/>size = 3]

        VM1[VM1<br/>LAMP + Apache]
        VM2[VM2<br/>LAMP + Apache]
        VM3[VM3<br/>LAMP + Apache]

        WEB[web page<br/>с ссылкой на image.jpg]
    end

    YC --> OS
    YC --> CC

    OS --> IMG
    CC --> IG

    IG --> VM1
    IG --> VM2
    IG --> VM3

    IMG -.-> WEB
    VM1 --> WEB
    VM2 --> WEB
    VM3 --> WEB