treeView-beta
netology/
├── stage0-bootstrap/   # Здесь создадим SA и Бакет
│   ├── main.tf
│   ├── variables.tf
│   └── outputs.tf
└── stage1-infra/       # Здесь будет основная инфраструктура (VPC, VMs)
    ├── main.tf
    ├── variables.tf
    └── ...