apiVersion: v1
kind: Service
metadata:
  name: {{ include "netology-app.fullname" . }}-frontend
  labels:
    {{- include "netology-app.labels" . | nindent 4 }}

spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/component: frontend
    {{- include "netology-app.selectorLabels" . | nindent 4 }}

  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80